name: Build (CI)

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"

jobs:
  setup-build-publish:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Protoc
        id: setup
        run: |
          sudo apt install -y protobuf-compiler && \
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: BuildWithTests
        id: build
        run: make test