name: Build (CI)

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"

jobs:
  setup-build-publish:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: BuildWithTests
        id: build
        run: make test